### ISSUE TITLE
Cannot receive open requests for pdf from Aquamail

### ISSUE THREAD

**Issue by Catfriend1** [JavaCafe01/PdfViewer#107]
### Steps to Reproduce the Problem

Receive aquamail email with a pdf attachment.
Click on pdf Attachment. 
Android pops up which pdf viewer to use selection.
Select MupdfViewer (works)
Select PdfviewerPlus (does not work, the app shows another chooser for which file manager to launch via android's dialog)

### Specifications

  - App Version:3.6 Fdroid
  - Android Version: 10 (miui12.1)

**Comment by Fs00** [comment]
Thanks for the report, I was able to reproduce the bug and will fix it very soon.

**Comment by JavaCafe01** [comment]
Fixed in #111
