### ISSUE TITLE
Network permissions

### ISSUE THREAD

**Issue by IzzySoft** [JavaCafe01/PdfViewer#115]
Could you please explain what your PDF Viewer requires network permission for? The app description does not tell, neither does your Readme here. Thanks in advance!

**Comment by deroke** [comment]
@IzzySoft  

Look at the code:
https://github.com/JavaCafe01/PdfViewer/blob/master/app/src/main/java/com/gsnathan/pdfviewer/DownloadPDFFile.java

**Comment by IzzySoft** [comment]
Well, I'm no Java developer. Yes, I assumed that a network connection is normally used to upload or, in this case, download things. But I cannot see the context, so I was hoping for a short explanation, @deroke. Like, what is downloaded from where and why. OK, going by the names some PDF is downloaded. When does that happen? Where does the URL come from?

When an app I assume working "locally only" requests `INTERNET` permission, it raises an eyebrow for me. So it would be much appreciated to transparently mention the background – so that very same eyebrow can easily be lowered again – which I assume will be the case here :wink:

**Comment by deroke** [comment]
If you open a PDF file on web (e.g. https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) **PDF Viewer Plus** will be opened and need to download the passed URL:

https://github.com/JavaCafe01/PdfViewer/blob/0ae811394ce0c68ab04fab43eac90d7658b4ea35/app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java#L322-L326



This happens because there is an `<intent-filter>` 

https://github.com/JavaCafe01/PdfViewer/blob/0ae811394ce0c68ab04fab43eac90d7658b4ea35/app/src/main/AndroidManifest.xml#L22-L33

which opens **PDF Viewer Plus**

**Comment by IzzySoft** [comment]
Thanks! For the end-user: could that be added to the app description and/or Readme, like:

> Permissions required:
>
> * `INTERNET`: can open PDFs from links passed to it (e.g. when you tap an URL pointing to a PDF)
> * Storage: save downloaded PDFs, open stored PDFs

Further, the app declares `android.permission.WRITE_INTERNAL_STORAGE` – are you sure there even is such a permission? I've saw that pop up here and there for years, but never found it in any reference. AFAIK the opposite to `*_EXTERNAL_STORAGE` is `*_MEDIA_STORAGE`.

**Comment by Fs00** [comment]
> Further, the app declares android.permission.WRITE_INTERNAL_STORAGE – are you sure there even is such a permission?

You're right, that permission does not exist. It does not even make sense because an app is free to read and write whatever it wants from its internal storage space inside `/data/data` folder.
I've pushed a commit to #114 to remove it.

**Comment by JavaCafe01** [comment]
Updated README with permissions

**Comment by IzzySoft** [comment]
Thanks a lot! That should definitely solve the issue (to give some background: I've stumbled on this during one of our reviews at F-Droid; disclosure: I'm one of the F-Droid maintainers).
