### ISSUE TITLE
Open PDF Files directly from File Manager

### ISSUE THREAD

**Issue by JVariance** [JavaCafe01/PdfViewer#117]
# Current Behaviour:

If I click on a pdf file in Samsung's file manager, PDFViewer opens file selector/directory view.

# Expected Behaviour:

PDFViewer opens the clicked PDF file.

__
## Device informations

Device: Samsung Galaxy S7
Android version: 8.0.0

**Comment by Fs00** [comment]
This has already been fixed (#111), will come with the next release.

**Comment by JVariance** [comment]
Perfect 👍
