### ISSUE TITLE
crash at bigger PDF files

### ISSUE THREAD

**Issue by herrdeh** [JavaCafe01/PdfViewer#120]
### Issue Summary
App crashes when opening bigger files

### Steps to Reproduce the Problem
Open a PDF of ~1MB of size. 
Scroll
Flip orientation by 90°
Crash

### Specifications

  - App Version: 3.6
  - Android Version: LineageOS 14.1, Android 7.1.2
  - LG G3S - **1GB of RAM** - this may be an essential info

Here are 2 matlogs - HTH...
[2021-04-20-16-49-09.txt](https://github.com/JavaCafe01/PdfViewer/files/6345753/2021-04-20-16-49-09.txt) 
[2021-04-20-16-52-11.txt](https://github.com/JavaCafe01/PdfViewer/files/6345749/2021-04-20-16-52-11.txt)

**Comment by Fs00** [comment]
From your logcat I see:
```
04-20 16:48:15.370 W/art     (7535): Throwing OutOfMemoryError "Failed to allocate a 262156 byte allocation with 240688 free bytes and 235KB until OOM"
04-20 16:48:15.370 E/Bitmap  (7535): OOM allocating Bitmap with dimensions 256 x 256
04-20 16:48:15.374 W/JNIHelp (7535): Discarding pending exception (java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 240688 free bytes and 235KB until OOM) to throw java/lang/OutOfMemoryError
04-20 16:48:15.379 E/AndroidRuntime(7535): FATAL EXCEPTION: PDF renderer
04-20 16:48:15.379 E/AndroidRuntime(7535): Process: com.gsnathan.pdfviewer, PID: 7535
04-20 16:48:15.379 E/AndroidRuntime(7535): java.lang.OutOfMemoryError
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.graphics.Bitmap.nativeCreate(Native Method)
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at com.github.barteksc.pdfviewer.h.d()
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at com.github.barteksc.pdfviewer.h.handleMessage()
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.os.Looper.loop(Looper.java:154)
04-20 16:48:15.379 E/AndroidRuntime(7535): 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-20 16:48:15.386 W/ActivityManager(955):   Force finishing activity com.gsnathan.pdfviewer/.MainActivity_
04-20 16:48:15.396 W/ActivityManager(955):   Force finishing activity com.gsnathan.pdfviewer/.MainActivity_
```

So yes, there seems not to be enough RAM.
If you have high quality rendering enabled, you may try to disable it to see if the situation improves.

**Comment by JavaCafe01** [comment]
@herrdeh Most, if not all, modern smart phones have a little bit more RAM than 1 GB, so because of that, I'm going to close this issue. This does not mean I'm not supporting phones with low specs - as this problem only occurs when loading huge PDF files.

To help with the loading you can disable high quality rendering, as said above.

**Comment by herrdeh** [comment]
I already had disabled "high quality rendering" before -  nevertheless crashes occur as mentioned. Now, I deactivated anti-aliasing as well, which actually improved the situation. But with larger files, crashes still are frequent.
IMHO, supporting older phones is a valuable measure of sustainability - but of course it's always debatable how far one can go with that.
Thank you for your effort!

**Comment by Fs00** [comment]
#9 might also improve the situation for low memory devices.
