### ISSUE TITLE
[Suggestion] List of last opened PDFs

### ISSUE THREAD

**Issue by beriain** [JavaCafe01/PdfViewer#13]
Hi! First of all I would want to thank you for developing this great PDF viewer.

I have a suggestion, I think it would be helpful to have a list of the last opened files in the main screen instead of the lorem ipsum sample file. What do you think about it?

**Comment by Echolon** [comment]
Thought the same recently!

**Comment by JavaCafe01** [comment]
There is a huge update coming, I'll add this onto my list. I have a lot of things going on, the update will come in about two weeks or so

**Comment by worksfourme** [comment]
Hi, I had the same idea that having a list of the last opened files would be really useful. But I would like to add something:

I'd suggest to put the Last opened PDFs list into this kind of menu on the left-hand side of the screen that can be opened by swiping from the edge of the screen. (That thing with the "three horizontal bars" as it's icon on the left of the title bar.)
I think it would make it far easier to switch documents without always having to go back to the start screen. This way you can also open another document over your first one just to look up something quickly and then get back to your main document only by pressing back. Too make this nicely usable, the app also had to rember the position in the document you go back to, so you don't have to search for it again.

**Comment by Fs00** [comment]
@JavaCafe01 I stumbled upon this issue which can now be considered solved.
Now when the app is launched, the system file picker gets opened, which includes a way to pick a recently opened document from the drawer.

**Comment by JavaCafe01** [comment]
Closed as file picker opens on launch (which contains recently open documents)
