### ISSUE TITLE
[Suggestion] RU-localization

### ISSUE THREAD

**Issue by Greynar** [JavaCafe01/PdfViewer#14]
I just wanna suggest russian localization to you, may be you will need it. :)

[strings — ru.txt](https://github.com/JavaCafe01/PdfViewer/files/2917177/strings.ru.txt)

**Comment by JavaCafe01** [comment]
Thank you very much! I will update the app soon and make sure you're listed as a contributor.

**Comment by JavaCafe01** [comment]
All done, you're contribution will be available on Version 2.8
