### ISSUE TITLE
Android 10 : pdf files are not accessible by the app

### ISSUE THREAD

**Issue by gbdomubpkm** [JavaCafe01/PdfViewer#140]
OS on an ANDROID 10 base, all versions of PdfViewer i think : 

Unable to select (and thus open a file) through the app.
![image20210816_180225217](https://user-images.githubusercontent.com/50362604/129596167-685914ff-2b3c-475f-9332-67e16401e201.jpg)

It seems to me that it worked on the android 9 base.

Pdfviewer has the proper permissions enabled i think as, on the other hand, a pdf file can be opened without problem (open with) with your app by the file manager !

Can you confirm ? Thanks.

**Comment by user8446** [comment]
I'm on Android 10 and it works. Make sure the storage permission is on.

**Comment by gbdomubpkm** [comment]
Really a coincidence but the problem was fixed by a critical bug update today of my Android 10 based OS (but not Android 10).
This very good pdfViewer app was totally out of the question.
This app has everything to grow.
So I close the issue.
