### ISSUE TITLE
[suggestion] sharing

### ISSUE THREAD

**Issue by infinitytec** [JavaCafe01/PdfViewer#16]
### Issue Summary

There is no way to share a file directly from the app. It would be nice to have.

### Specifications

  - App Version: 2.7
  - Android Version: 8.0

**Comment by JavaCafe01** [comment]
@infinitytec there is on version 2.7, if you click the fab menu on the bottom you will see a share file icon.

**Comment by infinitytec** [comment]
Oh, my bad!

**Comment by mr-gosh** [comment]
Ok - this "+" is not used the right way - as i also ran into not clicking it at all on the search for the share dialog...
