### ISSUE TITLE
The "+" icon obstructs the view

### ISSUE THREAD

**Issue by kuba-orlik** [JavaCafe01/PdfViewer#17]
### Issue Summary

Today, I couldn't scan a train ticket because of the "+" icon:

![D1xHHnvXQAA3RIm](https://user-images.githubusercontent.com/2697916/54478345-4e7d7700-4811-11e9-8604-d0bbd3591616.jpg)

### Specifications

  - App Version: 2.7
  - Android Version: 8.1.0 (Lineage OS + microg)

**Comment by JavaCafe01** [comment]
The plus icon contains all the extra options, I might just redesign the main interface of the app. Any recommendations? I'm planning on putting everything on a bottom app bar...

**Comment by JavaCafe01** [comment]
Ofc with the new configuration nothing will block the main pdf view

**Comment by kuba-orlik** [comment]
I'd be fine with just being able to toggle the "+" icon by tapping anywhere in the document view, or moving all the options to the "three dots" menu

**Comment by Fs00** [comment]
@JavaCafe01 We don't have the FAB anymore, I think this can be closed.
