### ISSUE TITLE
[Suggestion] Add Full Screen Mode

### ISSUE THREAD

**Issue by neolovich** [JavaCafe01/PdfViewer#18]
Hello!
A full screen mode/read mode would be a nice feature. For example, you tap once at the PDF and the toolbar on top of the pdf, the navigation bar and the status bar disappears (or appears if the full screen mode is enabled).
Or toolbar, navigation bar and status bar disappear automatically after a few seconds.

Its only a wish/suggestion. I dont know how much work it is.

Thanks a lot for your work until now :smiley: :+1: 
 
### Specifications

  - App Version: 2.7
  - Android Version: Lineage 15.1.

**Comment by emanchado** [comment]
At least [Document Viewer](https://f-droid.org/en/packages/org.sufficientlysecure.viewer/) has that, and it's really useful! Source code, in case it's useful, is available on [GitHub](https://github.com/SufficientlySecure/document-viewer).

**Comment by ericschdt** [comment]
It would already increase the UX a lot, if the the big, unnecessary toolbar were hidden by default. :)

**Comment by thosoo** [comment]
This one is quite necessary to read in landscape mode. On my phone this toolbar eats 20% of the screen.. Maybe hiding the bar through scrolling would be cool.

**Comment by pascoual** [comment]
Need it too!

**Comment by JavaCafe01** [comment]
Implemented in #116

**Comment by HyknuF** [comment]
Hi, just stumpled upon the fullscreenmode which is nice, but wouldn't it be more useful to have the fullscreenmode actived per default and show the bar on toggle press?  at least myself, I almost always want to view pdf files with the most viewable screenspace possible :-)

thanks in advance!
