### ISSUE TITLE
"Source Code" link leads to a different project

### ISSUE THREAD

**Issue by Rovod** [JavaCafe01/PdfViewer#2]
https://github.com/JavaCafe01/PdfViewer/blob/3c2f1800477a05814def66e2beae005e1629784c/app/src/main/java/com/gsnathan/pdfviewer/AboutActivity.java#L200

**Comment by JavaCafe01** [comment]
Good catch, thanks!

**Comment by JavaCafe01** [comment]
Fixed in https://github.com/JavaCafe01/PdfViewer/commit/18b6d8e779006b83820fe63318b6c700d8aba10e
