### ISSUE TITLE
Add share intent

### ISSUE THREAD

**Issue by mr-gosh** [JavaCafe01/PdfViewer#20]
There is no pdf viewer for Android that is able to share the opened file.to another Intent.

If I open an pdf from an e-mail i open it to check what to do with it - and normally i want to share it than to something like my owncloud instance or something like this.

I think this is an easy but productive feature that other pdf readers are missing.

**Comment by horstle** [comment]
The feature already exists. #16

**Comment by JavaCafe01** [comment]
Indeed it does... thanks @horstle

**Comment by mr-gosh** [comment]
Well yes it does - but it is unintuitive to find, perhaps the floating icon should get three points and not the plus ...
