### ISSUE TITLE
[PdfViewer][v2.8]The app crashes if i enable navigation color.

### ISSUE THREAD

**Issue by maaudrana** [JavaCafe01/PdfViewer#24]
<h4>Actual  Behaviour </h4>
App  crashes if i enable navigation  bar color.
<h4>Expected behavior</h4>
Expected  that i can enable navigation bar color without crashing the app.</h4>
<ol>
<li>Install  and open the app</li>
<li>click three horizontal dot in top bar.</li>
<li>Click change theme</li>
<li>Enable Navigation bar color.</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v2.8</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/wZ2TxkJdiC4">https://youtu.be/wZ2TxkJdiC4</a>
<h4>LogCat</h4>
<pre>
<code>
06-03 06:54:01.271  6252  6252 E AndroidRuntime: FATAL EXCEPTION: main
06-03 06:54:01.271  6252  6252 E AndroidRuntime: Process: com.gsnathan.pdfviewer, PID: 6252
06-03 06:54:01.271  6252  6252 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at com.jaredrummler.cyanea.b.e.m(Unknown Source:83)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at com.jaredrummler.cyanea.b.e.b(Unknown Source:8)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at com.jaredrummler.cyanea.a.d.onStart(Unknown Source:7)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7348)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3139)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-03 06:54:01.271  6252  6252 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</code>
</pre>

**Comment by maaudrana** [comment]
@JavaCafe01 can you give feedback with my created issue?add bug level if these bug_reports are valid.

**Comment by JavaCafe01** [comment]
@maaudrana I just found about the error, it's fixed now. Play Store update is live for 2.9.
