### ISSUE TITLE
[PdfViewer][v2.8]The app crashes i click back icon from about page.

### ISSUE THREAD

**Issue by maaudrana** [JavaCafe01/PdfViewer#26]
<h4>Actual  Behaviour </h4>
App  crashes if i click back icon from about page.
<h4>Expected behavior</h4>
Expected  that i can go back successfully without crashing the app</h4>
<ol>
<li>Install  and open the app</li>
<li>Load a pdf by clicking "+" sign(you must laod a pdf to reproduce the bug).</li>
<li>click three horizontal dot in the top</li>
<li>Click about</li>
<li>Click Replay intro.</li>
<li>After replaying click the back icon from page</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v2.8</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/4AxtB4ilb3s">https://youtu.be/4AxtB4ilb3s</a>
<h4>LogCat</h4>
<pre>
<code>
06-03 06:55:07.894  8155  8155 E AndroidRuntime: FATAL EXCEPTION: main
06-03 06:55:07.894  8155  8155 E AndroidRuntime: Process: com.gsnathan.pdfviewer, PID: 8155
06-03 06:55:07.894  8155  8155 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at com.jaredrummler.cyanea.b.e.m(Unknown Source:83)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at com.jaredrummler.cyanea.b.e.b(Unknown Source:8)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at com.jaredrummler.cyanea.a.d.onStart(Unknown Source:7)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7348)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3139)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-03 06:55:07.894  8155  8155 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</code>
</pre>

**Comment by JavaCafe01** [comment]
Same as
https://github.com/JavaCafe01/PdfViewer/issues/25

**Comment by maaudrana** [comment]
Hey! I just Checked out the last version 3.0 but still the crash occurring. 
To reproduce the bug,follow  step again.

**Comment by maaudrana** [comment]
Oh i see issue #25 has been solved but this issue is not fixed so how they are same?

**Comment by JavaCafe01** [comment]
Ok, now i finally see the error, this is my bad... @maaudrana

**Comment by JavaCafe01** [comment]
@maaudrana my logs showed a different error, basically, it said that the about page was restricted from opening the document and going back to the already open document. What's intriguing is that the hardware back button works perfectly. So I did a workaround and made the app bar back button act as the hardware one, and it now works on my emulator and phone. SHould be up soon, maybe tomorrow.
