### ISSUE TITLE
[FR] reflow mode

### ISSUE THREAD

**Issue by ildar** [JavaCafe01/PdfViewer#29]
Please add the mode like in MuPDF (Lightweight document viewer) - https://f-droid.org/app/com.artifex.mupdfdemo or in Book Reader (Simple book reader) - https://f-droid.org/app/com.github.axet.bookreader

**Comment by Yutsa** [comment]
What do you mean by `reflow mode` exactly ?

**Comment by ildar** [comment]
This is about showing text in a scalable manner, line length reorganized to
the viewing device (original PDF lengths usually too long).
Also search gave me this article with pictures:
https://www.quora.com/What-is-an-example-of-an-Android-PDF-reader-with-text-reflow

The list of apps can be appended by "KOReader"

**Comment by JavaCafe01** [comment]
I have been thinking of switching libraries to MuPDF, as said in #9
