### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by JavaCafe01** [JavaCafe01/PdfViewer#32]
@raspbeguy @Greynar

Again, thanks for your help on translations! I also would appreciate if you all would help in translating the play store descriptions also...

Here it is: 

```
A simple PDF document viewer.
--
Pdf Viewer Plus is an open source PDF viewer.
 
Features
--------------
<> Ability to open a PDF from anywhere
<> Ability to share a PDF
<> Many themes
```

**Comment by raspbeguy** [comment]
Hi, with pleasure.
In french:

```
Un lecteur simple de fichiers PDF.
--
Pdf Viewer Plus est un lecteur PDF open source.

Fonctionnalités
--------------
<> Permet d'ouvrir un PDF depuis n'importe où
<> Permet de partager un PDF
<> Beaucoup de thèmes
```

**Comment by Greynar** [comment]
Hey! 
In Russian, with love :) 

Простой ридер для PDF документов.

 Pdf Viewer Plus - это программа для просмотра PDF с открытым исходным кодом.
 
О приложении
- - - - - - - - - - - - - -
 <> Возможность открыть PDF из любого места
 <> Возможность поделиться PDF
 <> Большой выбор тем

**Comment by hajducsekb** [comment]
Hi! Here it is in Hungarian, if you need it:

```
Egy egyszerű pdf olvasó
--
A Pdf Viewer Plus egy nyílt forráskódú pdf olvasó. 
 
Funkciók:
--------------
<> PDF fájlok megnyitása bárhonnan
<> PDF fájlok megosztása
<> Sokféle kinézet
```
It's not the perfect translation, but I don't think I could do a much better one than this.

**Comment by JavaCafe01** [comment]
Thank you all for the help!
