### ISSUE TITLE
Application crashes on Android 10.

### ISSUE THREAD

**Issue by Forbo** [JavaCafe01/PdfViewer#41]
### Issue Summary

Application crashes on Android 10.

### Steps to Reproduce the Problem

As soon as you try to use the file picker the application crashes. If you try to open a PDF from another program's action it crashes. Uninstalled and reinstalled to no effect.

### Specifications

  - App Version: 3.1 via F-Droid
  - Android Version: 10

**Comment by ritlew** [comment]
Hopefully we can get a fix for this soon

**Comment by JavaCafe01** [comment]
I haven't done any Android 10 testing yet... hopefully I'll get to that soon.

**Comment by ioshomebrew** [comment]
Just tested the app on the Android 10 emulator and it worked fine

**Comment by Forbo** [comment]
It appears that this is now working correctly in version 3.2 via F-Droid. Closing issue.
