### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by jmue** [JavaCafe01/PdfViewer#44]
### Issue Summary

The applications crashes during start via launcher after some file via intent has been opened before

### Steps to Reproduce the Problem

- open some PDF through intent (E-Mail attachment)
- close application with back button
- open the application again from launcher

### Specifications

  - App Version: 3.2.23 (fdroid)
  - Android Version: 7.1/8.1

**Comment by PFayoux** [comment]
Could you tell which mail application you were using ? Is it Gmail ?

And if you can, could you give some log ?

**Comment by PFayoux** [comment]
Actually I guess it's not Gmail...

**Comment by jmue** [comment]
No, it was AOSP-mail, but that does not matter here. The crash also occurs when opening the PDF from file manager. So
- tap on pdf in file manager -> pdfviewer shows pdf
- close pdfviewer with back-button
- open pdfviewer from launcher -> pdfviewer crashes

No, unfortunally I do not have a log.

**Comment by PFayoux** [comment]
It's very strange I don't reproduce on Android 9...
If you have time to do it (and actually can do it) you could try to catch the log with `adb logcat`.

**Comment by JavaCafe01** [comment]
Fixed in PR #72
