### ISSUE TITLE
text selection and copying to the clipboard

### ISSUE THREAD

**Issue by Sogolumbo** [JavaCafe01/PdfViewer#59]
### Summary
There should be the possibility to select text and copy it to the clipboard.
### Details
Usually long pressing on some text will select the text. This should also be true for this application.
There should be a selection with two cursors shown and an option to copy the selected text.
### Use case (one example)
I want to add an email address from a pdf to my address book. Clicking on the link opens my mailing app which doesn't allow me to copy the email address either.
This feature would allow me to copy the email address immediately.

**Comment by kofaysi** [comment]
Waits for major reworks:
https://github.com/JavaCafe01/PdfViewer/issues/9#issuecomment-626414111

**Comment by Cris--** [comment]
Yes please!

**Comment by JavaCafe01** [comment]
#9
