### ISSUE TITLE
Android does not show PDF Viewer as a PDF handler

### ISSUE THREAD

**Issue by stephenjudge** [JavaCafe01/PdfViewer#6]
Using Amaze as my file manager, if I tap a PDF file to open it, Android shows me the apps that can open this file, but PDF Viewer is not one of them.

**Comment by stephenjudge** [comment]
It seems it's a problem with the file name. I'll need to email you the name, I can't post it here.

**Comment by JavaCafe01** [comment]
@stephenjudge is it emailed yet?

**Comment by stephenjudge** [comment]
What address should I email you at?

**Comment by JavaCafe01** [comment]
> What address should I email you at?

gokulswamilive@gmail.cojm

**Comment by JavaCafe01** [comment]
Has been five days, I have not received an email.
