### ISSUE TITLE
Texts are not as crisp as mupdf

### ISSUE THREAD

**Issue by moshiur-raj** [JavaCafe01/PdfViewer#65]
### Issue Summary

 
![Screenshot_20201130-201223](https://user-images.githubusercontent.com/36466700/100620249-64fe9580-3348-11eb-8d90-64721eb2e4c7.png)
![Screenshot_20201130-201213](https://user-images.githubusercontent.com/36466700/100620339-83649100-3348-11eb-9977-7b7d0229d381.png)

I have high quality rendering and anti aliasing enabled.

### Specifications

  - App Version: 3.3
  - Android Version: 10

**Comment by JavaCafe01** [comment]
This issue is in regards of #9
