### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by Preisschild** [JavaCafe01/PdfViewer#7]
Awesome app, 
The last thing I need before I finally can ditch the last google app on my device (google PDF viewer) is printing.

In google PDF viewer I can print over the printers already added to my android system (so I guess this is native)
Can we implement this here?

**Comment by Preisschild** [comment]
This: https://developer.android.com/training/printing/custom-docs should be helpful.
If this isn't the top priority, no problem. I will take a look into it on the weekend. (I'm not a java dev though)

**Comment by JavaCafe01** [comment]
I have tried to implement it, but I get a runtime error when trying to print. It mentions that the pdf is a malformed pdf.

**Comment by Preisschild** [comment]
Can publish the changes you already did into a different branch?

**Comment by infinitytec** [comment]
I'd like this as well.

**Comment by JavaCafe01** [comment]
Just finished in 3dbf26c7c813ad65803cb0bd58d47ee8e735d119
