### ISSUE TITLE
[Suggestion] Allow multiple instances

### ISSUE THREAD

**Issue by Backfighter** [JavaCafe01/PdfViewer#8]
### Issue Summary

When opening a PDF the currently loaded PDF will be replaced by it. Instead it would be better to open the PDF in a new instance. This would allow multiple PDF to be open at the same time.

**Comment by JavaCafe01** [comment]
This is a difficult task, some help would be appreciated!

**Comment by Backfighter** [comment]
Basically we would have to start a new task every time a PDF is opened. 

In your Manifest that means setting launchMode to 'singleInstance'. This will result in the activity being started in a new task every time another applications launches it (e.g. when opening a PDF in the file explorer). 

I think that would suffice. But you will need to test what happens when you open a PDF from within your own app via the folder icon. I might look into your app in more detail when I've got the time. 

You can read more about this here: 
https://developer.android.com/guide/components/activities/tasks-and-back-stack#ManagingTasks

**Comment by JavaCafe01** [comment]
Thanks @Backfighter , I'll take a look into it today.

**Comment by JavaCafe01** [comment]
Fixed in #88
