### ISSUE TITLE
Bug: When you change the device orientation it exit the PDF reading

### ISSUE THREAD

**Issue by fux0r2009** [JavaCafe01/PdfViewer#93]
### Issue Summary

If the orientation of the phone changes, the PDF reading is exited and is asking again to choose a PDF file!

### Steps to Reproduce the Problem
Open the app
choose a pdf and open it 
then change the orientation of the device from vertical to horizontal (or vice versa) 
the pdf reading is lost and you are asked to choose the pdf file again

### Specifications

  - App Version: 3.5
  - Android Version: 10

PS: you are doing a wonderful job keep it up!! thanks :)

**Comment by Fs00** [comment]
This will be fixed when #92 gets merged (sorry, my fault!).

**Comment by fux0r2009** [comment]
thank you very much!

**Comment by JavaCafe01** [comment]
Fixed with #92 merge
