### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by JVariance** [JavaCafe01/PdfViewer#97]
A dark mode would be nice.
So that PDF is white text on black background. Maybe inverting does the trick.
I know, that there is an invert option in the OS, but this is way too inconveniant.

**Comment by JVariance** [comment]
This PDF Viewer (https://play.google.com/store/apps/details?id=eu.wanielista.pdfviewer) has it.
It inverts the colors when dark mode is switched on.

**Comment by JavaCafe01** [comment]
Hello! That app also uses the same back-end, so it should be very easy to add in a dark/night mode. I will add it soon!

**Comment by JVariance** [comment]
Awesome, thanks 🙌🏻

**Comment by JavaCafe01** [comment]
I'm going to keep this open, as I still need to define the color of the spacing between the pages (or i can just remove that spacing)

**Comment by JavaCafe01** [comment]
Done!
